"""Evidence admission regressions. Test files remain under ignored build/; no cleanup deletes."""
import unittest
import uuid
import xml.etree.ElementTree as ET

from acceptance import ROOT, validate_live_evidence


class LiveEvidenceTest(unittest.TestCase):
    def setUp(self):
        self.run = ROOT / "build/test-live-evidence" / uuid.uuid4().hex
        self.results = self.run / "sdk-test-results"
        self.results.mkdir(parents=True)
        self.payload = self.run / "target-event-payload.json"
        self.payload.write_text('[{"user": {}}]', encoding="utf-8")
        self.write_suite("LiveSyncIntegrationTest", ["streamingAgainstTargetServer",
            "pollingAgainstTargetServer", "targetServerStreamingOutagePollingAndStreamingRecovery"])
        self.write_suite("LiveEventIntegrationTest", ["eventsAgainstTargetAndExportExactPayloadForDomainValidation"])

    def write_suite(self, suite, methods, outcome=None):
        root = ET.Element("testsuite")
        for method in methods:
            case = ET.SubElement(root, "testcase", name=method)
            if outcome:
                ET.SubElement(case, outcome)
        ET.ElementTree(root).write(self.results / f"TEST-co.featbit.android.internal.{suite}.xml")

    def test_complete_live_evidence_is_admitted(self):
        validate_live_evidence(self.results, self.payload)

    def test_old_payload_cannot_replace_missing_current_payload(self):
        # A payload exists in another run; the requested run has produced none.
        with self.assertRaisesRegex(RuntimeError, "Missing payload generated by this live run"):
            validate_live_evidence(self.results, self.run / "new-run/target-event-payload.json")

    def test_empty_payload_is_rejected(self):
        self.payload.write_text("", encoding="utf-8")
        with self.assertRaisesRegex(RuntimeError, "Missing payload"):
            validate_live_evidence(self.results, self.payload)

    def test_missing_suite_or_method_is_rejected(self):
        with self.assertRaisesRegex(RuntimeError, "Missing live test evidence"):
            validate_live_evidence(self.run / "missing-results", self.payload)
        self.write_suite("LiveSyncIntegrationTest", ["streamingAgainstTargetServer"])
        with self.assertRaisesRegex(RuntimeError, "Live test did not pass"):
            validate_live_evidence(self.results, self.payload)

    def test_skipped_failed_or_error_test_is_rejected(self):
        for outcome in ("skipped", "failure", "error"):
            with self.subTest(outcome=outcome):
                self.write_suite("LiveEventIntegrationTest",
                    ["eventsAgainstTargetAndExportExactPayloadForDomainValidation"], outcome)
                with self.assertRaisesRegex(RuntimeError, "Live test did not pass"):
                    validate_live_evidence(self.results, self.payload)


if __name__ == "__main__":
    unittest.main()
